name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: ./pdf-crud-app

      - name: Build
        run: npm run build
        working-directory: ./pdf-crud-app
        env:
          CI: ""

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./pdf-crud-app
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RTHM_F67E7 }}
          channelId: live
          projectId: rthm-f67e7
