name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies and build app
        run: |
          cd pdf-crud-app
          npm ci
          npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RTHM_F67E7 }}
          projectId: rthm-f67e7
          channelId: live
          # Specify the path to the firebase.json
          entryPoint: ./pdf-crud-app
          # Specify the build output folder
          target: pdf-crud-app/build
          firebaseToolsVersion: latest
